language: go
sudo: false
services:
  - docker
install:
  - curl https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | BINDIR=$GOPATH/bin sh
  - go mod download
script:
  - golangci-lint run --enable-all -D errcheck -D lll -D dupl -D gochecknoglobals --deadline 5m ./...
  - go test -coverprofile=coverage.txt -covermode=atomic -race -vet all ./...
  - travis-scripts/docker-build.bash
after_success:
  - bash <(curl -s https://codecov.io/bash)
go:
  - 1.x
  - tip
env:
  global:
    - GO111MODULE=on
    - GOPROXY=https://proxy.golang.org
matrix:
  allow_failures:
    - go: tip
