language: go
sudo: false
install:
  - go get github.com/alecthomas/gometalinter
  - gometalinter --install
  - go build -i
script:
  - gometalinter --vendor --disable errcheck --deadline 10m --cyclo-over 15 --tests
  - go test -coverprofile=coverage.txt -covermode=atomic -race
after_success:
  - bash <(curl -s https://codecov.io/bash)
go:
  - "1.10"
  - tip
matrix:
  allow_failures:
    - go: tip
