language: go
sudo: false
cache:
  directories:
    - $GOPATH/pkg
install:
  - go mod download
  - go get -v github.com/golangci/golangci-lint/cmd/golangci-lint@master
script:
  - golangci-lint run --enable-all -D errcheck -D lll -D dupl -D gochecknoglobals --deadline 5m ./...
  - go test -coverprofile=coverage.txt -covermode=atomic -race ./...
after_success:
  - bash <(curl -s https://codecov.io/bash)
go:
  - 1.x
  - tip
env:
  - GO111MODULE=on
