language: go
sudo: false
cache:
  directories:
    - $GOPATH/pkg
    - $GOPATH/bin
services:
  - docker
install:
  - go mod download
  - go get github.com/golangci/golangci-lint/cmd/golangci-lint@master
script:
  - golangci-lint run --enable-all -D errcheck -D lll -D dupl -D gochecknoglobals --deadline 5m ./...
  - go test -coverprofile=coverage.txt -covermode=atomic -race ./...
  - go build -o gcs-helper
after_success:
  - bash <(curl -s https://codecov.io/bash)
  - travis-scripts/docker-build.bash
go:
  - 1.x
  - tip
env:
  - GO111MODULE=on CGO_ENABLED=0
