language: go
sudo: false
install:
  - go get github.com/alecthomas/gometalinter
  - gometalinter --install
  - go build -i
script:
  - gometalinter --vendor --disable errcheck --deadline 10m --cyclo-over 15
  - go test -coverprofile=coverage.txt -covermode=atomic
after_success:
  - bash <(curl -s https://codecov.io/bash)
go:
  - 1.7.x
  - 1.8.x
  - tip
