language: go
sudo: false
install:
  - go get golang.org/x/lint/golint
  - go mod vendor
  - go build -i
  - golint -set_exit_status
script:
  - go test -coverprofile=coverage.txt -covermode=atomic -race
after_success:
  - bash <(curl -s https://codecov.io/bash)
go:
  - 1.11.x
  - tip
env:
  - GO111MODULE=on
matrix:
  allow_failures:
    - go: tip
