[[constraint]]
  name = "github.com/kelseyhightower/envconfig"
  version = "1.3.0"

[[constraint]]
  name = "github.com/sirupsen/logrus"
  version = "1.0.2"

[[constraint]]
  name = "cloud.google.com/go"
  version = "0.26.0"

[prune]
  unused-packages = true
  non-go = true
  go-tests = true
